# Zeabur 部署配置
# 指定后端使用 Python 3.11 版本，避免 pydantic-core 在 Python 3.13 上的编译问题

services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: PORT
        value: 8000
    healthCheckPath: /health
    rootDirectory: backend

  - type: web
    name: frontend
    env: static
    buildCommand: npm ci && npm run build
    publishDirectory: dist
    rootDirectory: frontend
    envVars:
      - key: VITE_API_URL
        value: https://backend.zeabur.app