# Zeabur 部署配置
# 使用 Dockerfile 指定后端使用 Python 3.11 版本，避免 pydantic-core 在 Python 3.13 上的编译问题

services:
  - type: web
    name: backend
    env: docker
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: PORT
        value: 8000
    healthCheckPath: /health
    # 设置构建上下文为项目根目录，以便访问 data 目录
    rootDirectory: .

  - type: web
    name: frontend
    env: static
    buildCommand: npm ci && npm run build
    publishDirectory: dist
    rootDirectory: frontend
    envVars:
      - key: VITE_API_URL
        value: https://backend.zeabur.app